export const NATIONALITIES = [
  { value: "Afghan", label: "Afghan" },
  { value: "Albanian", label: "Albanian" },
  { value: "Algerian", label: "Algerian" },
  { value: "Argentine", label: "Argentine" },
  { value: "Argentinian", label: "Argentinian" },
  { value: "Australian", label: "Australian" },
  { value: "Austrian", label: "Austrian" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Belgian", label: "Belgian" },
  { value: "Bolivian", label: "Bolivian" },
  { value: "Batswana", label: "Batswana" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Cambodian", label: "Cambodian" },
  { value: "Cameroonian", label: "Cameroonian" },
  { value: "Canadian", label: "Canadian" },
  { value: "Chilean", label: "Chilean" },
  { value: "Chinese", label: "Chinese" },
  { value: "Colombian", label: "Colombian" },
  { value: "Costa Rican", label: "Costa Rican" },
  { value: "Croatian", label: "Croatian" },
  { value: "Cuban", label: "Cuban" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Dominican", label: "Dominican" },
  { value: "Ecuadorian", label: "Ecuadorian" },
  { value: "Egyptian", label: "Egyptian" },
  { value: "Salvadorian", label: "Salvadorian" },
  { value: "English", label: "English" },
  { value: "Estonian", label: "Estonian" },
  { value: "Ethiopian", label: "Ethiopian" },
  { value: "Fijian", label: "Fijian" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },
  { value: "German", label: "German" },
  { value: "Ghanaian", label: "Ghanaian" },
  { value: "Greek", label: "Greek" },
  { value: "Guatemalan", label: "Guatemalan" },
  { value: "Haitian", label: "Haitian" },
  { value: "Honduran", label: "Honduran" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "Icelandic", label: "Icelandic" },
  { value: "Indian", label: "Indian" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Iranian", label: "Iranian" },
  { value: "Iraqi", label: "Iraqi" },
  { value: "Irish", label: "Irish" },
  { value: "Israeli", label: "Israeli" },
  { value: "Italian", label: "Italian" },
  { value: "Jamaican", label: "Jamaican" },
  { value: "Japanese", label: "Japanese" },
  { value: "Jordanian", label: "Jordanian" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Lao", label: "Lao" },
  { value: "Latvian", label: "Latvian" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Libyan", label: "Libyan" },
  { value: "Lithuanian", label: "Lithuanian" },
  { value: "Malagasy", label: "Malagasy" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Malian", label: "Malian" },
  { value: "Maltese", label: "Maltese" },
  { value: "Mexican", label: "Mexican" },
  { value: "Mongolian", label: "Mongolian" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Mozambican", label: "Mozambican" },
  { value: "Namibian", label: "Namibian" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "Dutch", label: "Dutch" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Nicaraguan", label: "Nicaraguan" },
  { value: "Nigerian", label: "Nigerian" },
  { value: "Norwegian", label: "Norwegian" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Panamanian", label: "Panamanian" },
  { value: "Paraguayan", label: "Paraguayan" },
  { value: "Peruvian", label: "Peruvian" },
  { value: "Philippine", label: "Philippine" },
  { value: "Polish", label: "Polish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Romanian", label: "Romanian" },
  { value: "Russian", label: "Russian" },
  { value: "Saudi", label: "Saudi" },
  { value: "Scottish", label: "Scottish" },
  { value: "Senegalese", label: "Senegalese" },
  { value: "Serbian", label: "Serbian" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "Slovak", label: "Slovak" },
  { value: "South African", label: "South African" },
  { value: "Korean", label: "Korean" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Sudanese", label: "Sudanese" },
  { value: "Swedish", label: "Swedish" },
  { value: "Swiss", label: "Swiss" },
  { value: "Syrian", label: "Syrian" },
  { value: "Taiwanese", label: "Taiwanese" },
  { value: "Tajikistani", label: "Tajikistani" },
  { value: "Thai", label: "Thai" },
  { value: "Tongan", label: "Tongan" },
  { value: "Tunisian", label: "Tunisian" },
  { value: "Turkish", label: "Turkish" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Emirati", label: "Emirati" },
  { value: "British", label: "British" },
  { value: "American **", label: "American **" },
  { value: "Uruguayan", label: "Uruguayan" },
  { value: "Venezuelan", label: "Venezuelan" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Welsh", label: "Welsh" },
  { value: "Zambian", label: "Zambian" },
  { value: "Zimbabwean", label: "Zimbabwean" },
];

export const areasByCity = {
  Lahore: ["Johar Town", "Gulberg", "Model Town", "DHA" , "Bahria Town"],
  Karachi: ["Clifton", "DHA", "Gulshan-e-Iqbal", "Nazimabad"],
  Islamabad: ["F-6", "F-7", "G-10", "I-8"],
};

export const locationOptions = [
  { value: "Karachi", label: "Karachi" },
  { value: "Lahore", label: "Lahore" },
  { value: "Faisalabad", label: "Faisalabad" },
  { value: "Rawalpindi", label: "Rawalpindi" },
  { value: "Multan", label: "Multan" },
  { value: "Hyderabad", label: "Hyderabad" },
  { value: "Gujranwala", label: "Gujranwala" },
  { value: "Peshawar", label: "Peshawar" },
  { value: "Rahim Yar Khan", label: "Rahim Yar Khan" },
  { value: "Quetta", label: "Quetta" },
  { value: "Muzaffarabad", label: "Muzaffarabad" },
  { value: "Battagram", label: "Battagram" },
  { value: "Kotli", label: "Kotli" },
  { value: "Islamabad", label: "Islamabad" },
  { value: "Bahawalpur", label: "Bahawalpur" },
  { value: "Sargodha", label: "Sargodha" },
  { value: "Sialkot", label: "Sialkot" },
  { value: "Sukkur", label: "Sukkur" },
  { value: "Larkana", label: "Larkana" },
  { value: "Shekhupura", label: "Shekhupura" },
  { value: "Bhimbar", label: "Bhimbar" },
  { value: "Jhang Sadr", label: "Jhang Sadr" },
  { value: "Gujrat", label: "Gujrat" },
  { value: "Mardan", label: "Mardan" },
  { value: "Malir Cantonment", label: "Malir Cantonment" },
  { value: "Kasur", label: "Kasur" },
  { value: "Mingora", label: "Mingora" },
  { value: "Dera Ghazi Khan", label: "Dera Ghazi Khan" },
  { value: "Sahiwal", label: "Sahiwal" },
  { value: "Nawabshah", label: "Nawabshah" },
  { value: "Okara", label: "Okara" },
  { value: "Mirpur Khas", label: "Mirpur Khas" },
  { value: "Chiniot", label: "Chiniot" },
  { value: "Shahkot", label: "Shahkot" },
  { value: "Kamoke", label: "Kamoke" },
  { value: "Saddiqabad", label: "Saddiqabad" },
  { value: "Burewala", label: "Burewala" },
  { value: "Jacobabad", label: "Jacobabad" },
  { value: "Muzaffargarh", label: "Muzaffargarh" },
  { value: "Muridke", label: "Muridke" },
  { value: "Jhelum", label: "Jhelum" },
  { value: "Shikarpur", label: "Shikarpur" },
  { value: "Hafizabad", label: "Hafizabad" },
  { value: "Kohat", label: "Kohat" },
  { value: "Khanpur", label: "Khanpur" },
  { value: "Khuzdar", label: "Khuzdar" },
  { value: "Dadu", label: "Dadu" },
  { value: "Gojra", label: "Gojra" },
  { value: "Mandi Bahauddin", label: "Mandi Bahauddin" },
  { value: "Tando Allahyar", label: "Tando Allahyar" },
  { value: "Daska Kalan", label: "Daska Kalan" },
  { value: "Pakpattan", label: "Pakpattan" },
  { value: "Bahawalnagar", label: "Bahawalnagar" },
  { value: "Tando Adam", label: "Tando Adam" },
  { value: "Khairpur Mir's", label: "Khairpur Mir's" },
  { value: "Chishtian", label: "Chishtian" },
  { value: "Abbottabad", label: "Abbottabad" },
  { value: "Jaranwala", label: "Jaranwala" },
  { value: "Ahmadpur East", label: "Ahmadpur East" },
  { value: "Vihari", label: "Vihari" },
  { value: "Kamalia", label: "Kamalia" },
  { value: "Kot Addu", label: "Kot Addu" },
  { value: "Khushab", label: "Khushab" },
  { value: "Wazirabad", label: "Wazirabad" },
  { value: "Dera Ismail Khan", label: "Dera Ismail Khan" },
  { value: "Chakwal", label: "Chakwal" },
  { value: "Swabi", label: "Swabi" },
  { value: "Lodhran", label: "Lodhran" },
  { value: "Nowshera Cantonment", label: "Nowshera Cantonment" },
  { value: "Charsadda", label: "Charsadda" },
  { value: "Jalalpur Jattan", label: "Jalalpur Jattan" },
  { value: "Mianwali", label: "Mianwali" },
  { value: "Chaman", label: "Chaman" },
  { value: "Kandhkot", label: "Kandhkot" },
  { value: "Hasilpur", label: "Hasilpur" },
  { value: "Arifwala", label: "Arifwala" },
  { value: "Mianke Mor", label: "Mianke Mor" },
  { value: "Attock City", label: "Attock City" },
  { value: "Chichawatni", label: "Chichawatni" },
  { value: "Bhakkar", label: "Bhakkar" },
  { value: "Kharian", label: "Kharian" },
  { value: "Layyah", label: "Layyah" },
  { value: "Kambar", label: "Kambar" },
  { value: "Moro", label: "Moro" },
  { value: "Mian Channun", label: "Mian Channun" },
  { value: "Turbat", label: "Turbat" },
  { value: "Shahdad Kot", label: "Shahdad Kot" },
  { value: "Bhalwal", label: "Bhalwal" },
  { value: "Dipalpur", label: "Dipalpur" },
  { value: "Badin", label: "Badin" },
  { value: "Pano Aqil", label: "Pano Aqil" },
  { value: "Kotri", label: "Kotri" },
  { value: "Tando Muhammad Khan", label: "Tando Muhammad Khan" },
  { value: "Harunabad", label: "Harunabad" },
  { value: "Pattoki", label: "Pattoki" },
  { value: "Chenab Nagar", label: "Chenab Nagar" },
  { value: "Kahror Pakka", label: "Kahror Pakka" },
  { value: "Gujar Khan", label: "Gujar Khan" },
  { value: "Kot Malik Barkhurdar", label: "Kot Malik Barkhurdar" },
  { value: "Chuchar-kana Mandi", label: "Chuchar-kana Mandi" },
  { value: "Toba Tek Singh", label: "Toba Tek Singh" },
  { value: "Narowal", label: "Narowal" },
  { value: "Shorkot", label: "Shorkot" },
  { value: "Shahdadpur", label: "Shahdadpur" },
  { value: "Shabqadar", label: "Shabqadar" },
  { value: "Mansehra", label: "Mansehra" },
  { value: "Shujaabad", label: "Shujaabad" },
  { value: "Haveli Lakha", label: "Haveli Lakha" },
  { value: "Lala Musa", label: "Lala Musa" },
  { value: "Mailsi", label: "Mailsi" },
  { value: "Shakargarh", label: "Shakargarh" },
  { value: "Ghotki", label: "Ghotki" },
  { value: "Sibi", label: "Sibi" },
  { value: "Jampur", label: "Jampur" },
  { value: "Sambrial", label: "Sambrial" },
  { value: "Sanghar", label: "Sanghar" },
  { value: "Hujra Shah Muqim", label: "Hujra Shah Muqim" },
  { value: "Kabirwala", label: "Kabirwala" },
  { value: "Chunian", label: "Chunian" },
  { value: "Sangla Hill", label: "Sangla Hill" },
  { value: "Haripur", label: "Haripur" },
  { value: "Nankana Sahib", label: "Nankana Sahib" },
  { value: "Pasrur", label: "Pasrur" },
  { value: "Gwadar", label: "Gwadar" },
  { value: "Rajanpur", label: "Rajanpur" },
  { value: "Rohri", label: "Rohri" },
  { value: "Zhob", label: "Zhob" },
  { value: "Matli", label: "Matli" },
  { value: "Rawala Kot", label: "Rawala Kot" },
  { value: "Hadali", label: "Hadali" },
  { value: "Mirpur Mathelo", label: "Mirpur Mathelo" },
  { value: "Bannu", label: "Bannu" },
  { value: "Dullewala", label: "Dullewala" },
  { value: "Hala", label: "Hala" },
  { value: "Ratodero", label: "Ratodero" },
  { value: "Jatoi Shimali", label: "Jatoi Shimali" },
  { value: "Jauharabad", label: "Jauharabad" },
  { value: "Bat Khela", label: "Bat Khela" },
  { value: "Kot Radha Kishan", label: "Kot Radha Kishan" },
  { value: "Kahna Nau", label: "Kahna Nau" },
  { value: "Mustafabad", label: "Mustafabad" },
  {
    value: "Chak Thirty-one -Eleven Left",
    label: "Chak Thirty-one -Eleven Left",
  },
  { value: "Talagang", label: "Talagang" },
  { value: "Taunsa", label: "Taunsa" },
  { value: "Thatta", label: "Thatta" },
  { value: "Sarai Alamgir", label: "Sarai Alamgir" },
  { value: "Usta Muhammad", label: "Usta Muhammad" },
  { value: "Kamra", label: "Kamra" },
  { value: "Umarkot", label: "Umarkot" },
  { value: "Basirpur", label: "Basirpur" },
  { value: "Sehwan", label: "Sehwan" },
  { value: "Naushahra Virkan", label: "Naushahra Virkan" },
  { value: "Fort Abbas", label: "Fort Abbas" },
  { value: "Havelian", label: "Havelian" },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Dinga", label: "Dinga" },
  { value: "Ladhewala Waraich", label: "Ladhewala Waraich" },
  { value: "Khalabat", label: "Khalabat" },
  { value: "New Badah", label: "New Badah" },
  { value: "Tank", label: "Tank" },
  { value: "Kot Mumin", label: "Kot Mumin" },
  { value: "Tandlianwala", label: "Tandlianwala" },
  { value: "Chak Azam Sahu", label: "Chak Azam Sahu" },
  { value: "Loralai", label: "Loralai" },
  { value: "Jalalpur Pirwala", label: "Jalalpur Pirwala" },
  { value: "Pabbi", label: "Pabbi" },
  { value: "Chak Jhumra", label: "Chak Jhumra" },
  { value: "Sahiwal", label: "Sahiwal" },
  { value: "Renala Khurd", label: "Renala Khurd" },
  { value: "Risalpur Cantonment", label: "Risalpur Cantonment" },
  { value: "Lakki", label: "Lakki" },
  { value: "Topi", label: "Topi" },
  { value: "Hangu", label: "Hangu" },
  { value: "Pir Jo Goth", label: "Pir Jo Goth" },
  { value: "Kundian", label: "Kundian" },
  { value: "Pir Mahal", label: "Pir Mahal" },
  { value: "Khurrianwala", label: "Khurrianwala" },
  { value: "Mehrabpur", label: "Mehrabpur" },
  { value: "Pindi Bhattian", label: "Pindi Bhattian" },
  { value: "Malakwal City", label: "Malakwal City" },
  { value: "Narang Mandi", label: "Narang Mandi" },
  { value: "Malakwal", label: "Malakwal" },
  { value: "Thul", label: "Thul" },
  { value: "Pindi Gheb", label: "Pindi Gheb" },
  { value: "Zahir Pir", label: "Zahir Pir" },
  { value: "Dunyapur", label: "Dunyapur" },
  { value: "Gambat", label: "Gambat" },
  { value: "Kashmor", label: "Kashmor" },
  { value: "Alipur", label: "Alipur" },
  { value: "Naudero", label: "Naudero" },
  { value: "Pasni", label: "Pasni" },
  { value: "Sukheke Mandi", label: "Sukheke Mandi" },
  { value: "Setharja Old", label: "Setharja Old" },
  { value: "Khewra", label: "Khewra" },
  { value: "Mamu Kanjan", label: "Mamu Kanjan" },
  { value: "Sharqpur Sharif", label: "Sharqpur Sharif" },
  { value: "Digri", label: "Digri" },
  { value: "Bhera", label: "Bhera" },
  { value: "Sakrand", label: "Sakrand" },
  { value: "Tando Jam", label: "Tando Jam" },
  { value: "Raiwind", label: "Raiwind" },
  { value: "Lalian", label: "Lalian" },
  { value: "Khairpur Tamewah", label: "Khairpur Tamewah" },
  { value: "Kharan", label: "Kharan" },
  { value: "Mehar", label: "Mehar" },
  { value: "Khangah Dogran", label: "Khangah Dogran" },
  { value: "Khairpur Nathan Shah", label: "Khairpur Nathan Shah" },
  { value: "Upper Dir", label: "Upper Dir" },
  { value: "Ghauspur", label: "Ghauspur" },
  { value: "Tangi", label: "Tangi" },
  { value: "Utmanzai", label: "Utmanzai" },
  { value: "Thal", label: "Thal" },
  { value: "Minchianabad", label: "Minchianabad" },
  { value: "Garh Maharaja", label: "Garh Maharaja" },
  { value: "Jahanian Shah", label: "Jahanian Shah" },
  { value: "Mastung", label: "Mastung" },
  { value: "Mananwala", label: "Mananwala" },
  { value: "Fazilpur", label: "Fazilpur" },
  { value: "Talamba", label: "Talamba" },
  { value: "Kunjah", label: "Kunjah" },
  { value: "Jhawarian", label: "Jhawarian" },
  { value: "Nasirabad", label: "Nasirabad" },
  { value: "Nushki", label: "Nushki" },
  { value: "Sita Road", label: "Sita Road" },
  { value: "Dijkot", label: "Dijkot" },
  { value: "Sillanwali", label: "Sillanwali" },
  { value: "Kandiaro", label: "Kandiaro" },
  { value: "Zaida", label: "Zaida" },
  { value: "Kunri", label: "Kunri" },
  { value: "Kalat", label: "Kalat" },
  { value: "Daud Khel", label: "Daud Khel" },
  { value: "Mitha Tiwana", label: "Mitha Tiwana" },
  { value: "Hazro City", label: "Hazro City" },
  { value: "Dunga Bunga", label: "Dunga Bunga" },
  { value: "Aman Garh", label: "Aman Garh" },
  { value: "Karor", label: "Karor" },
  { value: "Kot Diji", label: "Kot Diji" },
  { value: "Kalur Kot", label: "Kalur Kot" },
  { value: "Murree", label: "Murree" },
  { value: "Faqirwali", label: "Faqirwali" },
  { value: "Ahmadpur Sial", label: "Ahmadpur Sial" },
  { value: "Phalia", label: "Phalia" },
  { value: "Yazman", label: "Yazman" },
  { value: "Raja Jang", label: "Raja Jang" },
  {
    value: "Chak Five Hundred Seventy-five",
    label: "Chak Five Hundred Seventy-five",
  },
  { value: "Pishin", label: "Pishin" },
  {
    value: "Chak One Hundred Twenty Nine Left",
    label: "Chak One Hundred Twenty Nine Left",
  },
  { value: "Chawinda", label: "Chawinda" },
  { value: "Ubauro", label: "Ubauro" },
  { value: "Mithi", label: "Mithi" },
  { value: "Akora", label: "Akora" },
  { value: "Zafarwal", label: "Zafarwal" },
  { value: "Kot Samaba", label: "Kot Samaba" },
  { value: "Eminabad", label: "Eminabad" },
  { value: "Kahuta", label: "Kahuta" },
  { value: "Ranipur", label: "Ranipur" },
  { value: "Kulachi", label: "Kulachi" },
  { value: "Khanpur Mahar", label: "Khanpur Mahar" },
  { value: "Hingorja", label: "Hingorja" },
  { value: "Naukot", label: "Naukot" },
  { value: "Pind Dadan Khan", label: "Pind Dadan Khan" },
  { value: "Kanganpur", label: "Kanganpur" },
  { value: "Faruka", label: "Faruka" },
  { value: "Kotli Loharan", label: "Kotli Loharan" },
  { value: "Shahpur Chakar", label: "Shahpur Chakar" },
  { value: "Talhar", label: "Talhar" },
  { value: "Pad Idan", label: "Pad Idan" },
  { value: "Kot Ghulam Muhammad", label: "Kot Ghulam Muhammad" },
  { value: "Qadirpur Ran", label: "Qadirpur Ran" },
  { value: "Bela", label: "Bela" },
  { value: "Surkhpur", label: "Surkhpur" },
  { value: "Dhoro Naro", label: "Dhoro Naro" },
  { value: "Khangarh", label: "Khangarh" },
  { value: "Sarai Naurang", label: "Sarai Naurang" },
  { value: "Gharo", label: "Gharo" },
  { value: "Bhit Shah", label: "Bhit Shah" },
  { value: "Matiari", label: "Matiari" },
  { value: "Dhanot", label: "Dhanot" },
  { value: "Warah", label: "Warah" },
  { value: "Lachi", label: "Lachi" },
  { value: "Baddomalhi", label: "Baddomalhi" },
  { value: "Jand", label: "Jand" },
  {
    value: "Chak Two Hundred Forty-nine Thal Development",
    label: "Chak Two Hundred Forty-nine Thal Development",
  },
  { value: "Dera Bugti", label: "Dera Bugti" },
  { value: "Tharu Shah", label: "Tharu Shah" },
  { value: "Naushahro Firoz", label: "Naushahro Firoz" },
  { value: "Dajal", label: "Dajal" },
  { value: "Daur", label: "Daur" },
  { value: "Bhopalwala", label: "Bhopalwala" },
  { value: "Paharpur", label: "Paharpur" },
  { value: "Bhan", label: "Bhan" },
  { value: "Mach", label: "Mach" },
  { value: "Goth Radhan", label: "Goth Radhan" },
  { value: "Uthal", label: "Uthal" },
  { value: "Kaleke Mandi", label: "Kaleke Mandi" },
  { value: "Jiwani", label: "Jiwani" },
  { value: "Johi", label: "Johi" },
  { value: "Chhor", label: "Chhor" },
  { value: "Mangla", label: "Mangla" },
  { value: "Bhawana", label: "Bhawana" },
  { value: "Shahr Sultan", label: "Shahr Sultan" },
  { value: "Jhol", label: "Jhol" },
  { value: "Sodhri", label: "Sodhri" },
  { value: "Kalabagh", label: "Kalabagh" },
  { value: "Sinjhoro", label: "Sinjhoro" },
  { value: "Kamar Mushani", label: "Kamar Mushani" },
  { value: "Kallar Kahar", label: "Kallar Kahar" },
  { value: "Chuhar Jamali", label: "Chuhar Jamali" },
  { value: "Harnoli", label: "Harnoli" },
  { value: "Sarai Sidhu", label: "Sarai Sidhu" },
  { value: "Choa Saidan Shah", label: "Choa Saidan Shah" },
  { value: "Dadhar", label: "Dadhar" },
  { value: "Darya Khan", label: "Darya Khan" },
  { value: "Daira Din Panah", label: "Daira Din Panah" },
  { value: "Garhiyasin", label: "Garhiyasin" },
  { value: "Madeji", label: "Madeji" },
  { value: "Dokri", label: "Dokri" },
  { value: "Sobhodero", label: "Sobhodero" },
  { value: "Dalbandin", label: "Dalbandin" },
  { value: "Daulatpur", label: "Daulatpur" },
  { value: "Bhag", label: "Bhag" },
  { value: "Rasulnagar", label: "Rasulnagar" },
  { value: "Chak", label: "Chak" },
  { value: "Shahpur", label: "Shahpur" },
  { value: "Tando Bago", label: "Tando Bago" },
  { value: "Baffa", label: "Baffa" },
  { value: "Karak", label: "Karak" },
  { value: "Garhi Khairo", label: "Garhi Khairo" },
  { value: "Lakhi", label: "Lakhi" },
  { value: "Gadani", label: "Gadani" },
  { value: "Surab", label: "Surab" },
  { value: "Rojhan", label: "Rojhan" },
  { value: "Ormara", label: "Ormara" },
  { value: "Chamber", label: "Chamber" },
  { value: "Kalaswala", label: "Kalaswala" },
  { value: "Islamkot", label: "Islamkot" },
  { value: "Liliani", label: "Liliani" },
  { value: "Bhiria", label: "Bhiria" },
  { value: "Mirwah Gorchani", label: "Mirwah Gorchani" },
  { value: "Dhaunkal", label: "Dhaunkal" },
  { value: "Daultala", label: "Daultala" },
  { value: "Diplo", label: "Diplo" },
  { value: "Kohlu", label: "Kohlu" },
  { value: "Harnai", label: "Harnai" },
  { value: "Jandiala Sher Khan", label: "Jandiala Sher Khan" },
  { value: "Daromehar", label: "Daromehar" },
  { value: "Mankera", label: "Mankera" },
  { value: "Sanjwal", label: "Sanjwal" },
  { value: "Miro Khan", label: "Miro Khan" },
  { value: "Gilgit", label: "Gilgit" },
  { value: "Kot Sultan", label: "Kot Sultan" },
  { value: "Khadro", label: "Khadro" },
  { value: "Berani", label: "Berani" },
  { value: "Begowala", label: "Begowala" },
  { value: "Tangwani", label: "Tangwani" },
  { value: "Bozdar Wada", label: "Bozdar Wada" },
  { value: "Jati", label: "Jati" },
  { value: "Rustam", label: "Rustam" },
  { value: "Darya Khan Marri", label: "Darya Khan Marri" },
  { value: "Sohbatpur", label: "Sohbatpur" },
  { value: "Doaba", label: "Doaba" },
  { value: "Mirpur Bhtoro", label: "Mirpur Bhtoro" },
  { value: "Sann", label: "Sann" },
  { value: "Samaro", label: "Samaro" },
  { value: "Barkhan", label: "Barkhan" },
  { value: "Bandhi", label: "Bandhi" },
  { value: "Karaundi", label: "Karaundi" },
  { value: "Mirpur Sakro", label: "Mirpur Sakro" },
  { value: "Adilpur", label: "Adilpur" },
  { value: "Bagarji", label: "Bagarji" },
  { value: "Goth Phulji", label: "Goth Phulji" },
  { value: "Rajo Khanani", label: "Rajo Khanani" },
  { value: "Alik Ghund", label: "Alik Ghund" },
  { value: "Dinan Bashnoian Wala", label: "Dinan Bashnoian Wala" },
  { value: "Jam Sahib", label: "Jam Sahib" },
  { value: "Kandiari", label: "Kandiari" },
  { value: "Kadhan", label: "Kadhan" },
  { value: "Goth Garelo", label: "Goth Garelo" },
  { value: "Nazir Town", label: "Nazir Town" },
  { value: "Khadan Khak", label: "Khadan Khak" },
  { value: "Pithoro", label: "Pithoro" },
  { value: "Duki", label: "Duki" },
  { value: "Nabisar", label: "Nabisar" },
  { value: "Kario Ghanwar", label: "Kario Ghanwar" },
  { value: "Parachinar", label: "Parachinar" },
];

export const industryOptions = [
  { value: "Accounting / Taxation", label: "Accounting / Taxation" },
  { value: "Advertising / PR", label: "Advertising / PR" },
  {
    value: "Agriculture / Fertilizer / Pesticide",
    label: "Agriculture / Fertilizer / Pesticide",
  },
  { value: "Apparel/Clothing", label: "Apparel/Clothing" },
  {
    value: "Architecture/Interior Design",
    label: "Architecture/Interior Design",
  },
  {
    value: "Artificial Intelligence (AI)",
    label: "Artificial Intelligence (AI)",
  },
  { value: "Arts / Entertainment", label: "Arts / Entertainment" },
  { value: "Automobile", label: "Automobile" },
  { value: "Aviation", label: "Aviation" },
  {
    value: "Banking/Financial Services",
    label: "Banking/Financial Services",
  },
  { value: "BPO", label: "BPO" },
  { value: "Broadcasting", label: "Broadcasting" },
  { value: "Business Development", label: "Business Development" },
  { value: "Call Center", label: "Call Center" },
  { value: "Chemicals", label: "Chemicals" },
  {
    value: "Construction / Cement / Metals",
    label: "Construction / Cement / Metals",
  },
  { value: "Consultants", label: "Consultants" },
  { value: "Courier / Logistics", label: "Courier / Logistics" },
  {
    value: "Distribution and Logistics",
    label: "Distribution and Logistics",
  },
  { value: "DropShip", label: "DropShip" },
  { value: "E-Commerce / E-Business", label: "E-Commerce / E-Business" },
  { value: "Education/Training", label: "Education/Training" },
  { value: "Electronics", label: "Electronics" },
  { value: "Engineering", label: "Engineering" },
  { value: "Event Management", label: "Event Management" },
  { value: "Fashion", label: "Fashion" },
  {
    value: "Fast Moving Consumer Goods (FMCG)",
    label: "Fast Moving Consumer Goods (FMCG)",
  },
  { value: "Food & Beverages", label: "Food & Beverages" },
  { value: "Gems & Jewellery", label: "Gems & Jewellery" },
  { value: "Government", label: "Government" },
  { value: "Health & Fitness", label: "Health & Fitness" },
  {
    value: "Healthcare / Hospital / Medical",
    label: "Healthcare / Hospital / Medical",
  },
  { value: "Hospitality", label: "Hospitality" },
  {
    value: "Hotel Management / Restaurants",
    label: "Hotel Management / Restaurants",
  },
  {
    value: "Importers / Distributors/Exporters",
    label: "Importers / Distributors/Exporters",
  },
  { value: "Information Technology", label: "Information Technology" },
  { value: "Insurance / Takaful", label: "Insurance / Takaful" },
  { value: "Investments", label: "Investments" },
  { value: "Law Firms/Legal", label: "Law Firms/Legal" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Media/Communications", label: "Media/Communications" },
  { value: "Mining / Petroleum", label: "Mining / Petroleum" },
  { value: "N.G.O./Social Services", label: "N.G.O./Social Services" },
  {
    value: "Oil & Gas / Natural Resources",
    label: "Oil & Gas / Natural Resources",
  },
  { value: "Packaging", label: "Packaging" },
  {
    value: "Personal Care and Services",
    label: "Personal Care and Services",
  },
  {
    value: "Pharmaceuticals / Clinical Research",
    label: "Pharmaceuticals / Clinical Research",
  },
  { value: "Power / Energy", label: "Power / Energy" },
  { value: "Project Management", label: "Project Management" },
  { value: "Publishing/Printing", label: "Publishing/Printing" },
  { value: "Real Estate/Property", label: "Real Estate/Property" },
  {
    value: "Recruitment / Employment Firms",
    label: "Recruitment / Employment Firms",
  },
  { value: "Retail", label: "Retail" },
  {
    value: "Security / Law Enforcement",
    label: "Security / Law Enforcement",
  },
  { value: "Services", label: "Services" },
  { value: "Shipping / Marine", label: "Shipping / Marine" },
  { value: "Telecommunication / ISP", label: "Telecommunication / ISP" },
  { value: "Textiles / Garments", label: "Textiles / Garments" },
  { value: "Tiles & Ceramics", label: "Tiles & Ceramics" },
  {
    value: "Travel/Tourism/Transportation",
    label: "Travel/Tourism/Transportation",
  },
  { value: "Warehousing", label: "Warehousing" },
  { value: "Other", label: "Other" },
];

export const monthOptions = [
  { value: "January", label: "January" },
  { value: "February", label: "February" },
  { value: "March", label: "March" },
  { value: "April", label: "April" },
  { value: "May", label: "May" },
  { value: "June", label: "June" },
  { value: "July", label: "July" },
  { value: "August", label: "August" },
  { value: "September", label: "September" },
  { value: "October", label: "October" },
  { value: "November", label: "November" },
  { value: "December", label: "December" },
];

export const experienceOptions = [
  { value: "Beginner", label: "Beginner" },
  { value: "Intermediate", label: "Intermediate" },
  { value: "Expert", label: "Expert" },
];

export const degreeOptions = [
  { value: "Non-Matriculation", label: "Non-Matriculation" },
  { value: "Matriculation/O-Level", label: "Matriculation/O-Level" },
  { value: "Intermediate/A-Level", label: "Intermediate/A-Level" },
  { value: "BA", label: "BA" },
  { value: "BE", label: "BE" },
  { value: "BFA", label: "BFA" },
  { value: "BBA", label: "BBA" },
  { value: "BS", label: "BS" },
  { value: "BSc", label: "BSc" },
  { value: "BEd", label: "BEd" },
  { value: "BCom", label: "BCom" },
  { value: "BCom Hons", label: "BCom Hons" },
  { value: "BDS", label: "BDS" },
  { value: "LLB", label: "LLB" },
  { value: "DNS", label: "DNS" },
  { value: "DVM", label: "DVM" },
  { value: "DPT", label: "DPT" },
  { value: "MA", label: "MA" },
  { value: "ME", label: "ME" },
  { value: "MS", label: "MS" },
  { value: "MSc", label: "MSc" },
  { value: "MEd", label: "MEd" },
  { value: "LLM", label: "LLM" },
  { value: "Masters in Business Administration", label: "MBA" },
  { value: "MCom", label: "MCom" },
  { value: "MCom Hons", label: "MCom Hons" },
  { value: "MFA", label: "MFA" },
  { value: "MPA", label: "MPA" },
  { value: "MBBS", label: "MBBS" },
  { value: "Pharm-D", label: "Pharm-D" },
  { value: "Mphil", label: "Mphil" },
  { value: "PHD", label: "PHD" },
  { value: "Diploma", label: "Diploma" },
  { value: "Certificate", label: "Certificate" },
  { value: "Short Course", label: "Short Course" },
];

export const CGPA_OUT_OF_OPTIONS = [
  { value: 4, label: "4.0" },
  { value: 5, label: "5.0" },
];

export const SALARY_RANGES = [
  "5,000 - 5,999",
  "6,000 - 6,999",
  "7,000 - 7,999",
  "8,000 - 8,999",
  "9,000 - 9,999",
  "10,000 - 10,999",
  "11,000 - 11,999",
  "12,000 - 12,999",
  "13,000 - 13,999",
  "14,000 - 14,999",
  "15,000 - 15,999",
  "16,000 - 16,999",
  "17,000 - 17,999",
  "18,000 - 18,999",
  "19,000 - 19,999",
  "20,000 - 24,999",
  "25,000 - 29,999",
  "30,000 - 34,999",
  "35,000 - 39,999",
  "40,000 - 44,999",
  "45,000 - 49,999",
  "50,000 - 59,999",
  "60,000 - 69,999",
  "70,000 - 79,999",
  "80,000 - 89,999",
  "90,000 - 99,999",
  "100,000 - 124,999",
  "125,000 - 149,999",
  "150,000 - 174,999",
  "175,000 - 199,999",
  "200,000 - 249,999",
  "250,000 - 299,999",
  "300,000 - 349,999",
  "350,000 - 399,999",
  "400,000 - 449,999",
  "450,000 - 499,999",
  "500,000 - 549,999",
  "550,000 - 599,999",
  "600,000 - 649,999",
  "650,000 - 699,999",
  "700,000 - 749,999",
  "750,000 - 799,999",
  "800,000 - 849,999",
  "850,000 - 899,999",
  "900,000 - 949,999",
  "950,000 - 999,999",
  "1,000,000+",
];

export const YEAR_OPTIONS = [
  { value: 2024, label: 2024 },
  { value: 2023, label: 2023 },
  { value: 2022, label: 2022 },
  { value: 2021, label: 2021 },
  { value: 2020, label: 2020 },
  { value: 2019, label: 2019 },
  { value: 2018, label: 2018 },
  { value: 2017, label: 2017 },
  { value: 2016, label: 2016 },
  { value: 2015, label: 2015 },
  { value: 2014, label: 2014 },
  { value: 2013, label: 2013 },
  { value: 2012, label: 2012 },
  { value: 2011, label: 2011 },
  { value: 2010, label: 2010 },
  { value: 2009, label: 2009 },
  { value: 2008, label: 2008 },
  { value: 2007, label: 2007 },
  { value: 2006, label: 2006 },
  { value: 2005, label: 2005 },
  { value: 2004, label: 2004 },
  { value: 2003, label: 2003 },
  { value: 2002, label: 2002 },
  { value: 2001, label: 2001 },
  { value: 2000, label: 2000 },
  { value: 1999, label: 1999 },
  { value: 1998, label: 1998 },
  { value: 1997, label: 1997 },
  { value: 1996, label: 1996 },
  { value: 1995, label: 1995 },
  { value: 1994, label: 1994 },
  { value: 1993, label: 1993 },
  { value: 1992, label: 1992 },
  { value: 1991, label: 1991 },
  { value: 1990, label: 1990 },
  { value: 1989, label: 1989 },
  { value: 1988, label: 1988 },
  { value: 1987, label: 1987 },
  { value: 1986, label: 1986 },
  { value: 1985, label: 1985 },
  { value: 1984, label: 1984 },
  { value: 1983, label: 1983 },
  { value: 1982, label: 1982 },
  { value: 1981, label: 1981 },
  { value: 1980, label: 1980 },
  { value: 1979, label: 1979 },
  { value: 1978, label: 1978 },
  { value: 1977, label: 1977 },
  { value: 1976, label: 1976 },
  { value: 1975, label: 1975 },
  { value: 1974, label: 1974 },
];


export const proficiencyOptions = [
  { value: "Beginner", label: "Beginner" },
  { value: "Intermediate", label: "Intermediate" },
  { value: "Expert", label: "Expert" },
];


export const Careerlevel = [
  "Intern/Student",
  "Entry Level",
  "Experienced Professional",
  "Department Head",
  "GM / CEO / Country Head / President"
]




